// @generated by protoc-gen-aelf-es v1.0.0 with parameter "target=ts"
// @generated from file reference/acs6.proto (package acs6, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BytesValue } from "@bufbuild/protobuf";


type SendMethodResponse = { TransactionId: string; };

type SendMethod = <P>(methodName: string, p: P) => Promise<SendMethodResponse>;

type ViewMethod = <P, R>(methodName: string, p: P) => Promise<R>;

/**
 * @generated from service acs6.RandomNumberProvideacsrContract
 */
export class RandomNumberProvideacsrContractClient {

  private callSendMethod: SendMethod;

  private callViewMethod: ViewMethod;

  constructor(callSendMethod: SendMethod, callViewMethod: ViewMethod) {
    this.callSendMethod = callSendMethod;
    this.callViewMethod = callViewMethod;
  }

    /**
     * @generated from rpc acs6.RandomNumberProvideacsrContract.GetRandomBytes
     */
  async GetRandomBytes(request: BytesValue): Promise<BytesValue> {
    // this is a view method
    return await this.callViewMethod<BytesValue, BytesValue>('GetRandomBytes', request);
    }
}
